### ISSUE TITLE
[Bug] Distillation column pressure drop units

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#345]
The pressure drop section in the distillation column does not reflect the selected pressure units, nor does it let one change the unit of measurement. See below where I am using psig for the rest of the simulation, but the pressure drop is fixed to bar and is greyed out so that I cannot change it:

![image](https://user-images.githubusercontent.com/9156129/176251034-dca759f6-49e1-4b30-8adf-c65ad26643c8.png)

**Comment by DanWBR** [comment]
@hdavid16 these boxes are only for indication. pressure drop has a different designation in the system of units - it doesn't use the same units as pressure.

**Comment by hdavid16** [comment]
They don't seem to be for indication. I specify values there to set the condenser and reboiler pressures. What I ended up doing is converting 10 psi to bar by hand and putting in the value in the Column Pressure Drop box. So I think the user should be able to select the units from the drop down.

**Comment by DanWBR** [comment]
@hdavid16 they do are for indication only - I didn't implement the function to change the units by changing the combobox values, which is why they are disabled.

As I wrote before, the units for pressure drop are different:

<img width="886" alt="Captura de Tela 2022-06-28 às 14 30 49" src="https://user-images.githubusercontent.com/2669419/176256690-9b19a8a1-248e-4fb2-8792-56e711b707b2.png">

not a bug - it was a design decision.

**Comment by hdavid16** [comment]
Ahh got it. Thanks!
