### ISSUE TITLE
[Improvement] Use Liquid Phase and Aqueous Phase instead of Liquid 1 and 2

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#38]
**Describe the issue**
DWSIM when shows results for three phase streams uses `liquid 1` and `liquid 2`. One example where it is confusing is three phase separator where DWSIM uses liquid 1 both for hydrocarbon outlet and water outlet. Instead I suggest **to use everywhere**

- Vapor phase
- Liquid phase
- Aqueous phase

See the below images for clarification. 
**Screenshots**

![DWSIM_emsVAyWMQc](https://user-images.githubusercontent.com/830394/95468291-36a99e80-0933-11eb-93ec-64fce35f5f52.png)

![DWSIM_8S7Bjq3PDP](https://user-images.githubusercontent.com/830394/95468342-41fcca00-0933-11eb-8253-ee7b9f58c157.png)

![DWSIM_4IlPh96z0G](https://user-images.githubusercontent.com/830394/95468381-4de88c00-0933-11eb-9d01-3c3131623bd9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - DWSIM 6.2
 - Classic UI

**Comment by DanWBR** [comment]
DWSIM has an Aqueous phase internally, but I chose to follow the CAPE-OPEN standard where the liquid phases are named Liquid1, Liquid2, Liquid3... and the liquid mixture is called Overall Liquid. The LL flash algorithms make no distinction if the second liquid phase is aqueous or not, as we may have a liquid phase split in a mixture without water.

**Comment by kookma** [comment]
Great! So, I think to prevent confusing we may need to report all phases for all streams. I have checked this in Hysys, and Symmetry. For example in Symmetry from Schlumberger, it has reported all phases and so if Liq0 is hydrocarbon liquid it is everywhere the same and Liq1 is aqueous phase. What do you think?

Example from Symmetry
![image](https://user-images.githubusercontent.com/830394/95495851-d4619580-0954-11eb-9e87-a6c0a0270e56.png)

**Comment by kookma** [comment]
**Consistency Across Flowsheet** 

Further to the above discussion, I notice inconsistency in displaying the results. For example see the below two cases. In the left the vapor outlet shows both vapor and liquid phase BUT at the left the vapor outlet only has vapor phase.


See the screenshot

- **Left**  vapor stream contains Vapor and Liquid 1 in results
- **Right** vapor stream contains Vapor only

![image](https://user-images.githubusercontent.com/830394/95516677-76dd4100-0974-11eb-986d-95fd2b6d4b2c.png)

**Comment by DanWBR** [comment]
@kookma this is not necessarily an inconsistency. Sometimes the flash algorithm calculates a residual liquid fraction, very small... I've fixed it in v6.1 Update 2 anyway.

**Comment by kookma** [comment]
Many thanks Daniel. 

Yes that is a mathematical error. Well we use DWSIM at the class! so we have to explain for students and they expect in a VLE flash, liquid goes to bottom and vapor goes to top :-)

**Comment by DanWBR** [comment]
I wouldn't say that it is a mathematical error. Before v6.2 Update 2, Even if the outlet streams of the separator were already well defined in terms of phases and compositions, DWSIM still did a Pressure-Enthalpy Flash to recalculate temperature, phase amounts and their compositions. Since the streams were in a saturated condition, with the stopping criteria being the enthalpy error between specified and calculated values as compared to a tolerance value (default 0.0001), DWSIM sometimes ended up calculating a very small amount of vapor or liquid, enough to display the phase and its properties, even if its amount was very small. 

https://github.com/DanWBR/dwsim6/blob/6c39e0d658407d48928cf1f0a2bb6853a0587b57/DWSIM.Thermodynamics/Flash%20Algorithms/NestedLoops.vb#L622

After v6.2 Update 2, a flag (AtEquilibrium) is set in the streams by the separator calculation so the flash calculation is bypassed, as we already know the phase of the stream, temperature, pressure, enthalpy, entropy and its composition:

https://github.com/DanWBR/dwsim6/blob/6c39e0d658407d48928cf1f0a2bb6853a0587b57/DWSIM.UnitOperations/Unit%20Operations/Vessel.vb#L631

**Comment by DanWBR** [comment]
To be more clear: before v6.2 Update 2, DWSIM had no idea that a stream coming out of the top of a separator vessel was 100% vapor. It only knew its Pressure, Enthalpy and Overall Composition, and then were told to calculate the corresponding Temperature and Phase Distribution. It was perfectly OK in most cases to have a liquid phase mole fraction of 1E-6 as a result of the equilibrium calculation, through it was unnecessary and could lead to errors if the downstream block required a single-phase stream...

**Comment by kookma** [comment]
Thanks Daniel! If I was right, after separator is solved, DWSIM performs  another flash calculation on the outlet streams! But after update 2 of v6.2, you bypassed this!

If my understanding is correct, then I think v6.2 u2 should work faster! I am in favor of update 2. After solving separator we know the conditions and compositions of outlet stream so they are solved!

**Comment by DanWBR** [comment]
@kookma,  yes, that's correct!

**Comment by DanWBR** [comment]
Sorry, where I wrote v6.1 Update 2, read v6.2 Update 2!

**Comment by kookma** [comment]
Thank you Daniel!
