### ISSUE TITLE
[Bug] Error on loading Component studies of old format

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#488]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When loading a component creator study of old format *.dwcsd" results in an error.

**To Reproduce**
Try to open attached file.

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**
File should be opened without error. File format should automatically be changed to new format of *.dwcsd2.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**
[3001 Sulfuric acid.zip](https://github.com/DanWBR/dwsim/files/11705714/3001.Sulfuric.acid.zip)

**Comment by DanWBR** [comment]
@Greg66 this file is very old and will not work in latest versions because it was saved in a binary format and some class names changed since then.

**Comment by Greg66** [comment]
How can old files be edited then? Create a tool for converting old files to new formats? From time to time file formats are changed (not only component studies). These old files with formats can't be used anymore. There seems no upward compatibility to be available.
There is still an option available to load these files with old format!

**Comment by DanWBR** [comment]
@Greg66 unfortunately there's not much I can do for older binary formats. That's why I created the XML/JSON formats so they can be read and adapted before loading/saving if necessary.

You can have multiple DWSIM versions installed to handle these files, though. For dwcsd files you can use an older version to load it, then export the component to XML or JSON - not sure what was the latest DWSIM version that supported it
