### ISSUE TITLE
[Feature Request]: Some Improvement on UI

### ISSUE THREAD

**Issue by kookma** [DanWBR/dwsim6#5]
1.  The selected compounds for a simulation shall be displayed at the top of list in Setting Window/ Compound. Right now you have to scroll all over the list to find them! A side panel to show selected compounds may be also useful!

2. Modal windows: Some DWSIM windows like Setting are modal. The issue is they stay over all open windows in current desktop while it shall only stay over open windows in DWSIM

3. Single click on objects in Flowsheet opens the Object Editors in the sidebar for editing object! This is not good as you may want to relocate object and single click is used to select the object. It is better to use double click for opening Object Editors.

4. Gas-Liquid Separator: Why the gas-liquid separator has 6 inlet streams! In industry we have no such cases even so, in simulation environment it is enough to use a mixer and the connect the outlet to mixer to separator

**Comment by AdrianDietz** [comment]
3-I will agree that opening the stream windows when moving is not necessary, at the same time I dont like double clicks, so this is not necessary a real improvement for every user.
4-I wrote in another post what I will copy here below:
I do not necessary agree on that, in practice one equipment can have more that one feed, even if temporary, secondly this feature allows avoiding a mixer and the unnecessary additional flash computation, when doing RTO or even Dynamics you reduce as much as possibles flashes that bring up non useful information. I have seen models with up to 15 inlets in a separator. By the way the hysys interface is far from perfect, not the same for the engine that is one of the industry references.
My statement would rather be, please allow more than six..

**Comment by DanWBR** [comment]
1 has always been the default behavior. Please add some instructions on how to reproduce this issue because in my tests and normal usage, the selected compounds always appear on top!

2 I think that there is no way to keep a window on top of other windows only inside the app, this is Windows Forms behavior.

3 was implemented a few months ago.

<img width="361" alt="Captura de Tela 2020-12-04 às 17 16 02" src="https://user-images.githubusercontent.com/2669419/101215571-756a8500-3654-11eb-8ec2-2d8134ee5189.png">

**Comment by DanWBR** [comment]
1, 2 and 3 were implemented. 4 won't be done.
