### ISSUE TITLE
Saturator Sample File Bug

### ISSUE THREAD

**Issue by Jamesincolorado** [DanWBR/dwsim6#79]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
I copied ti Python code into my file. Notice that the exit stream does not contain any water. 

**To Reproduce**
1. Go to attached file and unzip
2. run file
3. Open "Sat Gas" stream
4. See error: no water

**Expected behavior**
I ran this same stream in the original sample file and saw 1.5% water in the Sat Gas stream

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 3, 29 June 2007

**Additional context**
Parhaps there is a newer version?

[Saturator bug.zip](https://github.com/DanWBR/dwsim6/files/5745010/Saturator.bug.zip)

**Comment by andr1976** [comment]
Hi James 

If you untick the option to skip equilibrium calculations under settings, it calculates, but potentially underestimates water content
![image](https://user-images.githubusercontent.com/58475535/103283925-222ced80-49da-11eb-9f7b-4af28754fb2a.png)

I have attached a version where the python scripts forces the equilibrium calc (no need for the above then). The routine is not 100% fool-proof, since a water molefraction is set in the script order to generate a liquid phase, is this value is less than the water vapor pressure divded by total pressure at the given stream temperature then the gas will still be under-saturated. 
[saturator.zip](https://github.com/DanWBR/dwsim6/files/5750659/saturator.zip)
